["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "exercises"

["protostar.contracts"]
main = [
    "exercises/main.cairo",    
]
basic = [
    "exercises/contracts/basic/basic.cairo",    
]
